Repository Wego-A-Journey-Together/Wego-FE, pull requests merged in 2025-03, with the labels that each got.

#10 이슈 템플릿 추가
  .github/ISSUE_TEMPLATE/작업-내용-공유-템플릿.md
Labels: 📋 문서 정리

#21 Chore/config prettier
  .prettierrc
  eslint.config.mjs
  next.config.ts
  package.json
  pnpm-lock.yaml
Labels: 💬 중요 PR, ⚙️ 설정 관련 이슈

#31 Layout/home post list
  src/app/[lang]/layout.tsx
  src/app/[lang]/page.tsx
  src/components/Nav/NavBar.tsx
  src/components/common/RecruitPost.tsx
  src/components/home/InfiniteScroll.tsx
  src/components/home/TrendingCarousel.tsx
Labels: 🎨 디자인

#34 Layout/home filter selector
  package.json
  pnpm-lock.yaml
  public/icon/home/calenderIcon.svg
  public/icon/home/groupIcon.svg
  public/icon/home/openedBookIcon.svg
  public/icon/home/pinIcon.svg
  public/icon/home/smileIcon.svg
  public/image/dogProfile.png
  src/app/[lang]/page.tsx
  src/components/common/RecruitPost.tsx
  src/components/home/DatePicker.tsx
  src/components/home/DateSelect.tsx
  src/components/home/FilterSelector.tsx
  src/components/ui/button.tsx
  src/components/ui/calendar.tsx
  src/components/ui/checkbox.tsx
  src/components/ui/select.tsx
Labels: 🎨 디자인

#35 chore: 프리텐다드 전역 폰트 설정
  src/app/[lang]/layout.tsx
  src/app/globals.css
  src/fonts/PretendardVariable.woff2
Labels: 🎨 디자인, ⚙️ 설정 관련 이슈

#37 bug/responsive layout
  src/components/common/RecruitPost.tsx
  src/components/home/FilterSelector.tsx
  src/components/home/InfiniteScroll.tsx
  src/components/home/TrendingCarousel.tsx
Labels: 🐞 버그, 🎨 디자인

#43 feat : 홈 무한스크롤 내부 찜하기 버튼에 낙관적 업데이트 적용
  .gitignore
  .prettierrc
  .storybook/main.ts
  .storybook/preview.ts
  .storybook/vitest.setup.ts
  package.json
  pnpm-lock.yaml
  src/app/[lang]/profile/[userId]/page.tsx
  src/app/api/likes/[postId]/route.ts
  src/components/Btn/OptimisticUpdateLikes.stories.tsx
  src/components/Btn/OptimisticUpdateLikes.tsx
  src/components/common/RecruitPost.tsx
  src/components/home/DatePicker.tsx
  src/components/home/InfiniteScroll.tsx
  src/stories/Button.stories.ts
  src/stories/Button.tsx
  src/stories/Configure.mdx
  src/stories/Header.stories.ts
  src/stories/Header.tsx
  src/stories/Page.stories.ts
  src/stories/Page.tsx
  src/stories/assets/accessibility.png
  src/stories/assets/accessibility.svg
  src/stories/assets/addon-library.png
  src/stories/assets/assets.png
  src/stories/assets/avif-test-image.avif
  src/stories/assets/context.png
  src/stories/assets/discord.svg
  src/stories/assets/docs.png
  src/stories/assets/figma-plugin.png
  src/stories/assets/github.svg
  src/stories/assets/share.png
  src/stories/assets/styling.png
  src/stories/assets/testing.png
  src/stories/assets/theming.png
  src/stories/assets/tutorials.svg
  src/stories/assets/youtube.svg
  src/stories/button.css
  src/stories/header.css
  src/stories/page.css
  vitest.config.ts
Labels: 🔩 기능 추가

#45 design: '동행 모집하기' 글 작성 버튼 추가
  src/app/[lang]/page.tsx
  src/components/home/CreatePostWindow.tsx
Labels: 🎨 디자인

#42 fix: 홈화면 진입시 모집 글 페이지가 2번 로드되는 현상 수정
  .prettierrc
  src/components/home/InfiniteScroll.tsx
Labels: 🐞 버그

#48 feat: 네브바 반응형 디자인 및 검색 컴포넌트 개선
  src/app/[lang]/layout.tsx
  src/app/favicon.ico
  src/components/Btn/LoginBtn.tsx
  src/components/MultiLingual/MultiLingualToggler.tsx
  src/components/Nav/Hamburger.tsx
  src/components/Nav/Logo.tsx
  src/components/Nav/NavBar.tsx
  src/components/Nav/SearchBar.tsx
  src/hooks/useMediaQuery.ts
Labels: 🎨 디자인, 🔩 기능 추가

#50 design: 홈 화면의 필터 영역 반응형 1차 구현
  src/components/home/FilterSelector.tsx
  src/components/home/ReponsiveCalender.tsx
  src/components/ui/button.tsx
  src/components/ui/input.tsx
  tailwind.config.js
Labels: 🎨 디자인

#52 design: 상세페이지 레이아웃 분업
  public/data/trending.ts
  public/icon/detail/chatIcon.svg
  public/icon/detail/pinIcon.svg
  public/icon/detail/reviewStar.svg
  src/app/[lang]/buddy/[id]/page.tsx
  src/app/[lang]/detail/[id]/page.tsx
  src/app/[lang]/layout.tsx
  src/components/detail/PostContent.tsx
  src/components/detail/PostLocation.tsx
  src/components/detail/RecruitFooter.tsx
  src/components/detail/UserProfile.tsx
  src/components/home/TrendingCarousel.tsx
  src/components/ui/badge.tsx
  src/types/PostContent.ts
Labels: 🎨 디자인

#53 feat: 상세 페이지 탭 디자인, 네브바 수정, 충돌해결
  package.json
  pnpm-lock.yaml
  public/data/trending.ts
  src/app/[lang]/detail/[id]/page.tsx
  src/app/[lang]/detail/[id]/types.ts
  src/app/[lang]/layout.tsx
  src/components/Nav/Logo.tsx
  src/components/Nav/NavBar.tsx
  src/components/detail/PostContent.tsx
  src/components/detail/Tab.tsx
  src/components/detail/TabSection.tsx
  src/components/detail/UserProfile.tsx
Labels: 🎨 디자인

#54 fix: tab layout shift
  src/components/detail/Tab.tsx
  src/components/detail/TabSection.tsx
Labels: 🐞 버그

#58 refactor: 무한스크롤 개선 및 애니메이션 추가
  src/app/[lang]/page.tsx
  src/components/common/LoadingThreeDots.tsx
  src/components/home/CreatePostWindow.tsx
  src/components/home/InfiniteScroll.tsx
Labels: 🐞 버그, 🔧 코드 정리, ✨ 성능 개선

#63 refactor: 필터영역 컴포넌트로 분리, 리덕스를 통한 필터링 상태 관리
  public/icon/home/searchIcon.svg
  src/app/globals.css
  src/components/Btn/Like.tsx
  src/components/home/AddGroupButtonModal.tsx
  src/components/home/DatePicker.tsx
  src/components/home/FilterSelector.tsx
  src/components/home/RegionSelect.tsx
  src/components/home/ReponsiveCalender.tsx
  src/components/home/SortDateSelect.tsx
  src/components/home/filter/DateFilter.tsx
  src/components/home/filter/DesktopFilterOptions.tsx
  src/components/home/filter/GenderAndAgeFilter.tsx
  src/components/home/filter/GroupSizeFilter.tsx
  src/components/home/filter/GroupThemeFilter.tsx
  src/components/home/filter/LocationFilter.tsx
  src/components/home/filter/MobileFilterButton.tsx
  src/components/home/filter/MobileFilterModal.tsx
  src/components/home/filter/ScrollCalender.tsx
  src/components/home/filter/SearchButton.tsx
  src/components/ui/button.tsx
  src/redux/slices/filterSlice.ts
  src/redux/store.ts
Labels: 🔧 코드 정리, 🎨 디자인

#66 fix: 새로고침시 헤더가 깜빡이는 현상 해결
  public/data/trending.ts
  src/components/Nav/NavBar.tsx
  src/components/common/RecruitPost.tsx
  src/components/home/CreatePostWindow.tsx
  src/components/home/InfiniteScroll.tsx
  src/types/PostContent.ts
Labels: 🐞 버그, 🎨 디자인

#67 feat: 포스트 에디터 적용
  package.json
  pnpm-lock.yaml
  public/icon/search.png
  public/icon/search.svg
  src/app/[lang]/write/page.tsx
  src/app/globals.css
  src/components/Editor/CustomBulletList.tsx
  src/components/Editor/CustomOrderedList.tsx
  src/components/Editor/Tiptap.tsx
  src/components/Editor/Toolbar.tsx
  src/components/MultiLingual/MultiLingualToggler.tsx
  src/components/Nav/SearchBar.tsx
  src/components/home/CreatePostWindow.tsx
  src/components/home/InfiniteScroll.tsx
  src/components/ui/toggle.tsx
Labels: 🎨 디자인, 🔩 기능 추가

#70 design: 필터 영역, 달력 디자인 세부사항 적용
  public/icon/home/nextMonth.svg
  public/icon/home/prevMonth.svg
  src/components/Nav/SearchBar.tsx
  src/components/detail/RecruitFooter.tsx
  src/components/home/InfiniteScroll.tsx
  src/components/home/filter/DateFilter.tsx
  src/components/home/filter/GenderAndAgeFilter.tsx
  src/components/home/filter/GroupThemeFilter.tsx
  src/components/home/filter/LocationFilter.tsx
  src/components/home/filter/MobileFilterButton.tsx
  src/components/home/filter/ScrollCalender.tsx
  src/components/ui/button.tsx
  src/components/ui/calendar.tsx
  src/components/ui/input.tsx
  src/components/ui/select.tsx
Labels: 🎨 디자인

#71 chore: 깃허브 액션 기본 셋팅
  .github/ISSUE_TEMPLATE/issue-template.md
  .github/PULL_REQUEST_TEMPLATE/PR-main-template.md
  .github/workflows/ci.yml
Labels: ⚙️ 설정 관련 이슈

#72 fix: 깃허브 액션 테스트
  .github/pull_request_template.md
  .github/workflows/ci.yml
Labels: ⚙️ 설정 관련 이슈

#73 chore: 포크된 레포지토리에 싱크하는 액션 추가
  .github/workflows/sync-fork.yml
Labels: ⚙️ 설정 관련 이슈

#74 fix: 포크된 레포에서 액션 오류 수정
  .github/workflows/sync-fork.yml
Labels: ⚙️ 설정 관련 이슈

#75 fix: 포크된 레포에 싱크 문제 수정
  .github/workflows/sync-fork.yml
Labels: ⚙️ 설정 관련 이슈

#77 feat: 글 작성 페이지에 맞춘 미리보기 및 상세보기 데이터 바인딩
  package.json
  pnpm-lock.yaml
  public/data/trending.ts
  src/app/[lang]/write/page.tsx
  src/components/Editor/Tiptap.tsx
  src/components/common/RecruitPost.tsx
  src/components/detail/JsonToHtml.tsx
  src/components/detail/PostContent.tsx
  src/lib/extractPreview.ts
  src/lib/index.ts
Labels: 🔩 기능 추가

#78 design: 채팅장 ui 1차 구현
  src/app/[lang]/chat/[id]/page.tsx
  src/app/[lang]/chat/page.tsx
  src/app/[lang]/chat/tempData.ts
  src/app/[lang]/layout.tsx
  src/components/Nav/NavBar.tsx
  src/components/chat/ChatPreview.tsx
Labels: 🎨 디자인

#79 design: 프로필 페이지 초안, 컴포넌트 일부 분리
  public/icon/profile/defaltProfile.svg
  public/icon/profile/dropDown.svg
  public/icon/profile/profileEdit.svg
  public/icon/profile/proflieCheckIcon.svg
  src/app/[lang]/profile/[userId]/page.tsx
  src/components/Nav/Logo.tsx
  src/components/profile/MyGroupPost.tsx
  src/components/profile/MypageProfile.tsx
Labels: 🎨 디자인

#84 design: 프로필 페이지 내에 컴포넌트 추가
  public/data/review.ts
  public/icon/profile/closeIcon.svg
  public/icon/profile/defaultProfile.svg
  src/app/globals.css
  src/components/common/Divider.tsx
  src/components/detail/RecruitFooter.tsx
  src/components/profile/MyGroupPost.tsx
  src/components/profile/MyReview.tsx
  src/components/profile/MypageProfile.tsx
  src/components/profile/ProfileEditor.tsx
  src/components/profile/ReceivedReview.tsx
  src/components/ui/button.tsx
  src/components/ui/dialog.tsx
Labels: 🎨 디자인

#85 chore: multilingual darkmode
  src/app/[lang]/layout.tsx
  src/components/ThemeToggler/DarkModeToggler.tsx
Labels: 🔩 기능 추가

#92 design: 소감 작성하기 컴포넌트 제작 / 프로필 페이지 컴포넌트들 추가 및 연결
  public/icon/profile/uploadPhoto.svg
  src/components/common/Divider.tsx
  src/components/common/DividerLarge.tsx
  src/components/profile/DropDown.tsx
  src/components/profile/MyGroupPost.tsx
  src/components/profile/MyReview.tsx
  src/components/profile/MypageProfile.tsx
  src/components/profile/NoContentGuide.tsx
  src/components/profile/ProfileEditor.tsx
  src/components/profile/ReceivedReview.tsx
  src/components/profile/ReviewEditor.tsx
Labels: 🎨 디자인

#93 design: 글쓰기 페이지의 선호 정보 선택란 컴포넌트 제작
  src/app/[lang]/page.tsx
  src/app/[lang]/write/page.tsx
  src/components/Editor/PostSetupPanel.tsx
  src/components/home/filter/GroupThemeFilter.tsx
  src/components/profile/ConfirmMember.tsx
  src/components/profile/DropDown.tsx
  src/components/profile/GroupCreateByUser.tsx
  src/components/profile/MyComments.tsx
  src/components/ui/checkbox.tsx
Labels: 🎨 디자인
