Repository Wego-A-Journey-Together/Wego-FE, pull requests merged in 2025-04, with the labels that each got.

#95 design: 작성된 글의 썸네일 부분 추가, 달력들 기능 및 선택 범위 제한 수정
  public/data/trending.ts
  src/components/Editor/PostSetupPanel.tsx
  src/components/common/RecruitPost.tsx
  src/components/home/CreatePost.tsx
  src/components/home/InfiniteScroll.tsx
  src/components/home/filter/DateFilter.tsx
Labels: 🎨 디자인

#96 feat: 로그인 상태관리, GNB 상태
  src/app/[lang]/layout.tsx
  src/components/Nav/AuthNav.tsx
  src/components/Nav/Hamburger.tsx
  src/components/Nav/NavBar.tsx
  src/hooks/useSession.ts
  src/redux/ReduxProvider.tsx
  src/redux/slices/userSlice.ts
  src/redux/store.ts
Labels: 🎨 디자인, 🔩 기능 추가

#97 fix: fixed 요소 레이아웃 쉬프트 해결
  src/app/globals.css
  src/components/Nav/NavBar.tsx
Labels: 🐞 버그, 🎨 디자인

#98 style: 채팅창 슬라이더를 shadcn sheet으로 교체
  public/icon/profile/verifiedCheck.svg
  src/components/common/userChat.tsx
  src/components/detail/RecruitFooter.tsx
  src/components/profile/MyGroupPost.tsx
  src/components/profile/MypageProfile.tsx
  src/components/ui/sheet.tsx
Labels: 🔧 코드 정리

#101 feat: 프로필 편집 창 유효성 검사 추가
  src/components/profile/ProfileEditor.tsx
  src/components/profile/ReviewEditor.tsx
  src/components/ui/dialog.tsx
Labels: 🔩 기능 추가

#102 refactor: home detail
  src/app/[lang]/detail/[id]/page.tsx
  src/components/Btn/KAKAOLogin.tsx
  src/components/detail/JsonToHtml.tsx
  src/components/detail/JsonToHtmlWrapper.tsx
  src/components/detail/KakaoMapViewer.tsx
  src/components/detail/PostContent.tsx
  src/components/detail/PostLocation.tsx
  src/components/detail/RecruitFooter.tsx
  src/components/detail/TabSection.tsx
  src/components/detail/UserProfile.tsx
  src/components/home/TrendingCarousel.tsx
  src/lib/calculateDays.ts
  src/types/DetailPost.ts
Labels: 🔧 코드 정리

#103 fix: deadline date time
  src/components/common/RecruitPost.tsx
  src/components/common/userChat.tsx
  src/components/detail/RecruitFooter.tsx
  src/components/profile/MyGroupPost.tsx
  src/types/DetailPost.ts
  src/types/HomePost.ts
Labels: 🐞 버그, 🚨 도움 요청

#105 feat: 서버 무응답 방어코드 작성
  src/app/[lang]/layout.tsx
Labels: ✨ 성능 개선

#108 feat: 필터링 부분 쿼리파라미터로 전송
  src/app/[lang]/page.tsx
  src/app/[lang]/write/page.tsx
  src/app/api/filter/route.ts
  src/components/home/FilterSelector.tsx
  src/components/home/filter/DateFilter.tsx
  src/components/home/filter/GroupSizeFilter.tsx
  src/components/home/filter/MobileFilterModal.tsx
  src/components/home/filter/RecruitingCheckbox.tsx
  src/components/home/filter/ScrollCalender.tsx
  src/redux/slices/filterSlice.ts
Labels: 🔩 기능 추가

#115 feat: 프로필 이미지 업로드 기능 1차 구현 (보완 필요)
  public/icon/profile/defaultProfile.svg
  src/components/profile/ProfileEditor.tsx
Labels: 🔩 기능 추가

#116 chore: 다크모드시 강제 색상 변경
  src/app/globals.css
  src/components/home/CreatePostWindow.tsx
Labels: 🎨 디자인

#121 feat: 마이페이지에서 참여 신청 및 확정 관리, 내가 쓴 댓글 보기 1차 구현
  src/components/profile/ConfirmMember.tsx
  src/components/profile/MyComments.tsx
Labels: 🔩 기능 추가

#123 refactor: 홈페이지 무한 스크롤 영역, 찜 버튼 리팩토링
  src/app/[lang]/page.tsx
  src/app/api/likes/[postId]/route.ts
  src/components/Btn/Like.tsx
  src/components/common/LoginModal.tsx
  src/components/common/RecruitPost.tsx
  src/components/home/HomeSearch.tsx
  src/components/home/InfiniteScroll.tsx
  src/components/home/MockInfiniteScroll.tsx
  src/redux/slices/modalSlice.ts
  src/redux/store.ts
  src/types/BEHomePost.ts
Labels: 🔧 코드 정리, 👍 배포 준비

#126 feat: 채팅 기능 구현
  package.json
  pnpm-lock.yaml
  src/app/[lang]/chat/[kakaoId]/page.tsx
  src/app/[lang]/chat/[kakaoId]/tempData.ts
  src/components/common/ChatPageView.tsx
  src/components/common/ChatRoom.tsx
  src/components/common/userChat.tsx
  src/components/detail/RecruitFooter.tsx
  src/components/profile/MyComments.tsx
Labels: 🔩 기능 추가

#128 feat: 댓글 답글 (Read, Create) 완료
  src/components/Btn/AssignComment.tsx
  src/components/comment/CommentBundle.tsx
  src/components/comment/SingleComment.tsx
  src/components/detail/PostInput.tsx
Labels: 🚨 도움 요청, 🔩 기능 추가

#142 design: 상세페이지 참여 인원보기 추가
  src/components/common/RecruitPost.tsx
  src/components/detail/MemberSection.tsx
  src/components/detail/TabSection.tsx
  src/components/detail/UserProfile.tsx
Labels: 🎨 디자인

#145 feat: 필터링 기능 추가, 로고쪽 검색 기능과 컨플릭 해결, 채팅 메세지 시간 표시
  src/api/gatheringApi.ts
  src/app/[lang]/chat/[kakaoId]/page.tsx
  src/app/[lang]/liked/page.tsx
  src/components/Editor/PostSetupPanel.tsx
  src/components/chat/ChatPreview.tsx
  src/components/home/FilterSelector.tsx
  src/components/home/InfiniteScroll.tsx
  src/components/home/filter/GroupThemeFilter.tsx
Labels: 🔩 기능 추가
